### ISSUE TITLE
DisplayName not settable

### ISSUE THREAD

**Issue by tranpl** [IUCrimson/AspNet.Security.CAS#11]
Is the DisplayName option able to be added somehow? Previous version allowed for setting this property. I couldn't pull out the Caption property from the provider model, or its not available, just DisplayName and Name

**Comment by davidmdem** [comment]
To make sure I'm understanding correctly - you're wanting to override the `DisplayName` property on the `AuthenticationScheme` so that you can access a friendly login message, correct?

Assuming I'm correct, I think it was their intention for folks to use `DisplayName` in place of what used to be `Caption` in the Owin world.  

As of the 2.0 release, an overload was added to specify the `DisplayName` that is available when looking through Authentication Schemes that are registered.  Here's an example that I think is getting at what you want:

```c#
services
    .AddAuthentication()
    .AddCAS(CasDefaults.AuthenticationScheme, "Login with CAS", casOptions =>
    {
        casOptions.CasServerUrlBase = "https://youcas.server/cas";
    });
```

This will cause `DisplayName` to be set as "Login with CAS".

**Comment by tranpl** [comment]
Thank you very much! I overlooked.

**Comment by davidmdem** [comment]
Thank you!  It's honestly something I overlooked too when I made the 2.0 update.  It also made me realize that some of the things I ported over from the original Owin version of this middleware (like Caption) are no longer used.  I'll try to clean some of these things up.
