### ISSUE TITLE
backend logout support

### ISSUE THREAD

**Issue by cjdxhjj** [IUCrimson/AspNet.Security.CAS#13]
i didn't find any code process cas server logout request,it only provider a front end logout method,however 
when my app is deploy more then one node,the logout is not work,can you support this feature

**Comment by davidmdem** [comment]
Since the logout functionality is largely handled by the Cookie middleware, I'm not sure it's something that I can implement.

I am curious about what issues you're experiencing in a multi-node setup.  So that we're on the same page - does your logout method look something like this?

```c#

[HttpGet("logout")]
public async Task<IActionResult> Logout()
{
    // Removes the user's auth cookie for this site and domain. 
    await HttpContext.SignOutAsync();

    // Do a full CAS logout.  
    // This removes the user's CAS auth cookie from the CAS domain.
    return Redirect($"{_configuration["CasBaseUrl"]}/logout");
}

```

When I test this, my authentication cookie ('.AspNetCore.CookieSample` for the sample application) is removed as well as the CAS cookie from the CAS domain.

If a user returns to your site after this signout, they would not have `.AspNetCore.CookieSample` any more and should be re-challenged to sign in regardless of which node they hit when they return.

I don't currently have a multi-node setup to test this, so feel free to push back and help me reproduce/understand your setup and the behavior you're missing.
