### ISSUE TITLE
nginx proxy host error

### ISSUE THREAD

**Issue by taobaohi** [IUCrimson/AspNet.Security.CAS#15]
nginx proxy host error
i edit code  \AspNetCore.Security.CAS\CasHandler.cs
   private string BuildReturnTo(string state)
        {
           // var host = Request.Host;
            var host = "www.mydomain.com";
            return Request.Scheme + "://" + host +
                   Request.PathBase + Options.CallbackPath +
                   "?state=" + Uri.EscapeDataString(state);
        }
when   return url   http://www.mydomain.com/signin-cas?state=  error
Exception: Failed to retrieve user information from remote server.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__12.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()
-----------------------------------
Accept | text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
-- | --
Accept-Encoding | gzip, deflate
Accept-Language | zh-CN,zh;q=0.9
Cache-Control | max-age=0
Connection | close
Cookie | .AspNetCore.Correlation.CAS.EbNSSTqqmTbO5GCQDyPxL0Or6volOPdy-9r8FWT9ISw=N
Host | 127.0.0.1:63210
REMOTE-HOST | www.mydomain.com
Upgrade-Insecure-Requests | 1
User-Agent | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

**Comment by davidmdem** [comment]
It looks like you were running into the same issue as described in #16 where the desired domain name was not being set by `Request.Host`.  

I've added a [dev/2.0.3 branch](https://github.com/IUCrimson/AspNet.Security.CAS/tree/dev/2.0.3) that adds a `ServiceHost` option.  This should let you specify the FDQN used when constructing the `service` param.

```
.AddCAS(o =>
{
    o.CasServerUrlBase = Configuration["CasBaseUrl"];   // Set in `appsettings.json` file.
    o.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    o.ServiceHost = "www.mydomain.com";
});
```

If you could test that option out and see if it solves your need to manually override the host, that would be awesome.

Otherwise, I might suggest seeing if `var host =  new HostString("www.mydomain.com");` makes a difference.  

Also, I've seen that specific error when developing if I have a breakpoint hit and continue.  If you're seeing it while debugging with a break point, make sure to verify that it also throws without breakpoints set.

**Comment by NickDelBen** [comment]
This seems to be the exact problem I was having in #17  actually.

When nginx does a "proxy_pass" of the request  to your application server it can modify the hostname/address headers and other parts of the request to that of the target service. 

This results in the possibly losing information like the actual public hostname (www.example.com) and replacing it with an address or internal hostname.

This can lead to the host (name and port), the "scheme" and other parts being read incorrectly inside the provider.

This may also be the issue I was having where the proxy_pass changed the scheme to http, which results in the CAS server denying access because the service is not TLS secured.

**Comment by davidmdem** [comment]
If it's still relevant, the `2.0.3` release has added the `ServiceHost` and `ServiceForceHTTPS` options which should let you specify your application URL correctly.
