### ISSUE TITLE
error when returning to page after CAS login

### ISSUE THREAD

**Issue by joshb03** [IUCrimson/AspNet.Security.CAS#19]
XmlException: '=' is an unexpected token. The expected token is ';'. Line 85, position 407.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__12.MoveNext()

This is after making a copy of your sample project.  I set the CasBaseUrl correctly.  I can't tell what file is actually giving the error.

**Comment by davidmdem** [comment]
The error seems to suggest that it's trying to parse an HTML document instead of an XML CAS response in the ticket validator.  

It would be helpful if you could clone this repository and run the sample application with a breakpoint [here](https://github.com/IUCrimson/AspNet.Security.CAS/blob/master/src/AspNetCore.Security.CAS/Cas2TicketValidator.cs#L25) (I'm guessing that's where the error is) to see what you are getting for `responseBody`.

**Comment by johnabaranski** [comment]
Was able to resolve by changing the "CasBaseUrl": setting in appsettings.json to use https:// instead of http://.  I believe the invalid protocol response I was getting from our test CAS server was causing the error.

CAS requirements for "service" URL:
[https://apereo.github.io/cas/5.2.x/planning/Security-Guide.html#secure-transport-https](url)

**Comment by davidmdem** [comment]
@johnabaranski  Thanks for replying back with a solution!
